apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: whoami
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: whoami
  name: whoami
  namespace: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami
    spec:
      containers:
      - image: ghcr.io/nce/whoami:0b6ebe83c7f81725f46a2754a417c2b99f2243fb
        name: whoami
        ports:
        - containerPort: 80
          name: http
      imagePullSecrets:
      - name: ghcr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: whoami.klangregen.de
    kubernetes.io/ingress.class: nginx
  name: whoami-ingress
spec:
  rules:
  - host: whoami.klangregen.de
    http:
      paths:
      - backend:
          service:
            name: whoami-service
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - whoami.klangregen.de
    secretName: whoami-cert
