apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami
    spec:
      imagePullSecrets:
      - name: ghcr
      containers:
      - name: whoami
        image: ghcr.io/nce/whoami:foo
        ports:
        - containerPort: 80
          name: http
