apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
replicas:
- count: 2
  name: whoami
images:
- name: ghcr.io/nce/whoami
  newTag: 0b6ebe83c7f81725f46a2754a417c2b99f2243fb
