apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
replicas:
- count: 2
  name: whoami
images:
- name: ghcr.io/nce/whoami
  newTag: 09d5d816edb2a41c6523a356f272e6d0c2048e9f
