name: Build 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'www/**'
      - 'Dockerfile'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/arm64
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
        labels: ${{ github.event.repository.updated_at}}

    - uses: imranismail/setup-kustomize@v1
    - run: |
        cd k8s
        kustomize edit set image ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
        kustomize build --output prod/world.yaml
    - uses: EndBug/add-and-commit@v9
      with:
        message: "ci: set image tag to ${{ github.sha }}"
        push: true


